version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Seoul
    - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-docker
    - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
    - AIRFLOW__SMTP__SMTP_PORT=587
    - AIRFLOW__SMTP__SMTP_USER=${SMTP_USER}
    - AIRFLOW__SMTP__SMTP_PASSWORD=${SMTP_PASSWORD}
    - AIRFLOW__SMTP__SMTP_MAIL_FROM=${SMTP_USER}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
  depends_on:
    - postgres

services:
  dbt:
    build: ./dbt
    container_name: my-dbt
    volumes:
      - ./dbt:/usr/app/dbt
    working_dir: /usr/app/dbt
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["dbt", "run", "--profiles-dir", "/usr/app/dbt"]
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    image: postgres:13
    container_name: my-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    container_name: my-airflow-init
    command: >
      bash -c "airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com"

  airflow-webserver:
    <<: *airflow-common
    container_name: my-airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    container_name: my-airflow-scheduler
    command: scheduler

  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  crawler:
    build: ./crawler
    container_name: my-crawler
    volumes:
      - ./dataset:/app/output

  etl:
    build: .
    container_name: my-etl-container
    depends_on:
      - mysql
    volumes:
      - ./dataset:/app/dataset
      - ./model:/app/model
      - ./output:/app/output
    environment:
      - BASE_PATH=/app
      - INPUT_PATH=/app/dataset
      - OUTPUT_PATH=/app/output
      - MODEL_PATH=/app/model/win_predictor.pkl
      - MAPPING_PATH=/app/dataset/team_info.csv
      - ENCODING=cp949
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  mysql_data:
  postgres_data: